backend:
  name: github
  repo: curiouskitten/curiouskitten.github.io # 严格匹配你的仓库名
  branch: main # 如果你的主分支是 master，请改为 master

media_folder: "source/images" # 图片存放路径
public_folder: "/images"

collections:
  - name: "blog"
    label: "我的文章"
    folder: "source/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "日期", name: "date", widget: "datetime"}
      - {label: "正文", name: "body", widget: "markdown"}
